import type { Metadata } from 'next'

import { redirect } from 'next/navigation'
import { getServerSession } from 'next-auth'

import { redirectUri } from '@/constants'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession()

  if (session) return redirect(redirectUri)

  return children
}
