import type { TwHeight, TwScreenStyle, TwWidth } from '../types'

export const TW_WIDTH_SCREEN: TwScreenStyle<TwWidth> = {
  default: {
    fit: 'w-fit',
    full: 'w-full',
    screen: 'w-screen',
    auto: 'w-auto',
    half: 'w-1/2',
    wide: 'w-[256px]',
    none: '',
  },
  xs: {
    fit: 'xs:w-fit',
    full: 'xs:w-full',
    screen: 'xs:w-screen',
    auto: 'xs:w-auto',
    half: 'xs:w-1/2',
    wide: 'xs:w-[256px]',
    none: '',
  },
  sm: {
    fit: 'sm:w-fit',
    full: 'sm:w-full',
    screen: 'sm:w-screen',
    auto: 'sm:w-auto',
    half: 'sm:w-1/2',
    wide: 'sm:w-[256px]',
    none: '',
  },
  md: {
    fit: 'md:w-fit',
    full: 'md:w-full',
    screen: 'md:w-screen',
    auto: 'md:w-auto',
    half: 'md:w-1/2',
    wide: 'md:w-[256px]',
    none: '',
  },
  lg: {
    fit: 'lg:w-fit',
    full: 'lg:w-full',
    screen: 'lg:w-screen',
    auto: 'lg:w-auto',
    half: 'lg:w-1/2',
    wide: 'lg:w-[256px]',
    none: '',
  },
  xl: {
    fit: 'xl:w-fit',
    full: 'xl:w-full',
    screen: 'xl:w-screen',
    auto: 'xl:w-auto',
    half: 'xl:w-1/2',
    wide: 'xl:w-[256px]',
    none: '',
  },
} as const

export const TW_HEIGHT_SCREEN: TwScreenStyle<TwHeight> = {
  default: {
    fit: 'h-fit',
    full: 'h-full',
    screen: 'h-screen',
    auto: 'h-auto',
    half: 'h-1/2',
    none: '',
  },
  xs: {
    fit: 'xs:h-fit',
    full: 'xs:h-full',
    screen: 'xs:h-screen',
    auto: 'xs:h-auto',
    half: 'xs:h-1/2',
    none: '',
  },
  sm: {
    fit: 'sm:h-fit',
    full: 'sm:h-full',
    screen: 'sm:h-screen',
    auto: 'sm:h-auto',
    half: 'sm:h-1/2',
    none: '',
  },
  md: {
    fit: 'md:h-fit',
    full: 'md:h-full',
    screen: 'md:h-screen',
    auto: 'md:h-auto',
    half: 'md:h-1/2',
    none: '',
  },
  lg: {
    fit: 'lg:h-fit',
    full: 'lg:h-full',
    screen: 'lg:h-screen',
    auto: 'lg:h-auto',
    half: 'lg:h-1/2',
    none: '',
  },
  xl: {
    fit: 'xl:h-fit',
    full: 'xl:h-full',
    screen: 'xl:h-screen',
    auto: 'xl:h-auto',
    half: 'xl:h-1/2',
    none: '',
  },
} as const
