version: '3.8'
services:
  mongodb:
    image: mongo:7.0-jammy
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
    volumes:
      - ./local_db:/data/db
volumes:
  local_db:
