/* eslint-disable @typescript-eslint/padding-line-between-statements */
import type { ScreenStyle } from './screen'
import type { NumericRange, Width } from '@/types'

import tw from 'twin.macro'

export type GridColAmount = NumericRange<1, 12> | 'auto'
export type GridRowAmount = NumericRange<1, 6> | 'auto'
export type GridGapAmount = NumericRange<0, 12> | 0

export type GridColSpanAmount = NumericRange<1, 12> | 'auto'
export type GridColStartAmount = NumericRange<1, 13>

export type GridRowSpanAmount = NumericRange<1, 6>
export type GridRowStartAmount = NumericRange<1, 7>

// * Please note that the grid is not supported in IE11
/** Because this file too long,
 * * You can use shortcut `ctrl + k, ctrl + j` to fold the code
 * * And can use `ctrl + k, ctrl + 0` to unfold the code
 */
// Note: Please understand the tailwind why we are using this way to define the className

export const GRID_COL: ScreenStyle<GridColAmount> = {
  default: {
    auto: tw`grid-flow-col`,
    1: tw`grid-cols-1`,
    2: tw`grid-cols-2`,
    3: tw`grid-cols-3`,
    4: tw`grid-cols-4`,
    5: tw`grid-cols-5`,
    6: tw`grid-cols-6`,
    7: tw`grid-cols-7`,
    8: tw`grid-cols-8`,
    9: tw`grid-cols-9`,
    10: tw`grid-cols-10`,
    11: tw`grid-cols-11`,
    12: tw`grid-cols-12`,
  },
  xs: {
    auto: tw`xs:grid-flow-col`,
    1: tw`xs:grid-cols-1`,
    2: tw`xs:grid-cols-2`,
    3: tw`xs:grid-cols-3`,
    4: tw`xs:grid-cols-4`,
    5: tw`xs:grid-cols-5`,
    6: tw`xs:grid-cols-6`,
    7: tw`xs:grid-cols-7`,
    8: tw`xs:grid-cols-8`,
    9: tw`xs:grid-cols-9`,
    10: tw`xs:grid-cols-10`,
    11: tw`xs:grid-cols-11`,
    12: tw`xs:grid-cols-12`,
  },
  sm: {
    auto: tw`sm:grid-flow-col`,
    1: tw`sm:grid-cols-1`,
    2: tw`sm:grid-cols-2`,
    3: tw`sm:grid-cols-3`,
    4: tw`sm:grid-cols-4`,
    5: tw`sm:grid-cols-5`,
    6: tw`sm:grid-cols-6`,
    7: tw`sm:grid-cols-7`,
    8: tw`sm:grid-cols-8`,
    9: tw`sm:grid-cols-9`,
    10: tw`sm:grid-cols-10`,
    11: tw`sm:grid-cols-11`,
    12: tw`sm:grid-cols-12`,
  },
  md: {
    auto: tw`md:grid-flow-col`,
    1: tw`md:grid-cols-1`,
    2: tw`md:grid-cols-2`,
    3: tw`md:grid-cols-3`,
    4: tw`md:grid-cols-4`,
    5: tw`md:grid-cols-5`,
    6: tw`md:grid-cols-6`,
    7: tw`md:grid-cols-7`,
    8: tw`md:grid-cols-8`,
    9: tw`md:grid-cols-9`,
    10: tw`md:grid-cols-10`,
    11: tw`md:grid-cols-11`,
    12: tw`md:grid-cols-12`,
  },
  lg: {
    auto: tw`lg:grid-flow-col`,
    1: tw`lg:grid-cols-1`,
    2: tw`lg:grid-cols-2`,
    3: tw`lg:grid-cols-3`,
    4: tw`lg:grid-cols-4`,
    5: tw`lg:grid-cols-5`,
    6: tw`lg:grid-cols-6`,
    7: tw`lg:grid-cols-7`,
    8: tw`lg:grid-cols-8`,
    9: tw`lg:grid-cols-9`,
    10: tw`lg:grid-cols-10`,
    11: tw`lg:grid-cols-11`,
    12: tw`lg:grid-cols-12`,
  },
  xl: {
    auto: tw`xl:grid-flow-col`,
    1: tw`xl:grid-cols-1`,
    2: tw`xl:grid-cols-2`,
    3: tw`xl:grid-cols-3`,
    4: tw`xl:grid-cols-4`,
    5: tw`xl:grid-cols-5`,
    6: tw`xl:grid-cols-6`,
    7: tw`xl:grid-cols-7`,
    8: tw`xl:grid-cols-8`,
    9: tw`xl:grid-cols-9`,
    10: tw`xl:grid-cols-10`,
    11: tw`xl:grid-cols-11`,
    12: tw`xl:grid-cols-12`,
  },
} as const

export const GRID_ROW: ScreenStyle<GridRowAmount> = {
  default: {
    auto: tw`grid-flow-row`,
    1: tw`grid-rows-1`,
    2: tw`grid-rows-2`,
    3: tw`grid-rows-3`,
    4: tw`grid-rows-4`,
    5: tw`grid-rows-5`,
    6: tw`grid-rows-6`,
  },
  xs: {
    auto: tw`xs:grid-flow-row`,
    1: tw`xs:grid-rows-1`,
    2: tw`xs:grid-rows-2`,
    3: tw`xs:grid-rows-3`,
    4: tw`xs:grid-rows-4`,
    5: tw`xs:grid-rows-5`,
    6: tw`xs:grid-rows-6`,
  },
  sm: {
    auto: tw`sm:grid-flow-row`,
    1: tw`sm:grid-rows-1`,
    2: tw`sm:grid-rows-2`,
    3: tw`sm:grid-rows-3`,
    4: tw`sm:grid-rows-4`,
    5: tw`sm:grid-rows-5`,
    6: tw`sm:grid-rows-6`,
  },
  md: {
    auto: tw`md:grid-flow-row`,
    1: tw`md:grid-rows-1`,
    2: tw`md:grid-rows-2`,
    3: tw`md:grid-rows-3`,
    4: tw`md:grid-rows-4`,
    5: tw`md:grid-rows-5`,
    6: tw`md:grid-rows-6`,
  },
  lg: {
    auto: tw`lg:grid-flow-row`,
    1: tw`lg:grid-rows-1`,
    2: tw`lg:grid-rows-2`,
    3: tw`lg:grid-rows-3`,
    4: tw`lg:grid-rows-4`,
    5: tw`lg:grid-rows-5`,
    6: tw`lg:grid-rows-6`,
  },
  xl: {
    auto: tw`xl:grid-flow-row`,
    1: tw`xl:grid-rows-1`,
    2: tw`xl:grid-rows-2`,
    3: tw`xl:grid-rows-3`,
    4: tw`xl:grid-rows-4`,
    5: tw`xl:grid-rows-5`,
    6: tw`xl:grid-rows-6`,
  },
} as const

export const GRID_GAP: ScreenStyle<GridGapAmount> = {
  default: {
    0: tw`gap-0`,
    1: tw`gap-1`,
    2: tw`gap-2`,
    3: tw`gap-3`,
    4: tw`gap-4`,
    5: tw`gap-5`,
    6: tw`gap-6`,
    7: tw`gap-7`,
    8: tw`gap-8`,
    9: tw`gap-9`,
    10: tw`gap-10`,
    11: tw`gap-11`,
    12: tw`gap-12`,
  },
  xs: {
    0: tw`xs:gap-0`,
    1: tw`xs:gap-1`,
    2: tw`xs:gap-2`,
    3: tw`xs:gap-3`,
    4: tw`xs:gap-4`,
    5: tw`xs:gap-5`,
    6: tw`xs:gap-6`,
    7: tw`xs:gap-7`,
    8: tw`xs:gap-8`,
    9: tw`xs:gap-9`,
    10: tw`xs:gap-10`,
    11: tw`xs:gap-11`,
    12: tw`xs:gap-12`,
  },
  sm: {
    0: tw`sm:gap-0`,
    1: tw`sm:gap-1`,
    2: tw`sm:gap-2`,
    3: tw`sm:gap-3`,
    4: tw`sm:gap-4`,
    5: tw`sm:gap-5`,
    6: tw`sm:gap-6`,
    7: tw`sm:gap-7`,
    8: tw`sm:gap-8`,
    9: tw`sm:gap-9`,
    10: tw`sm:gap-10`,
    11: tw`sm:gap-11`,
    12: tw`sm:gap-12`,
  },
  md: {
    0: tw`md:gap-0`,
    1: tw`md:gap-1`,
    2: tw`md:gap-2`,
    3: tw`md:gap-3`,
    4: tw`md:gap-4`,
    5: tw`md:gap-5`,
    6: tw`md:gap-6`,
    7: tw`md:gap-7`,
    8: tw`md:gap-8`,
    9: tw`md:gap-9`,
    10: tw`md:gap-10`,
    11: tw`md:gap-11`,
    12: tw`md:gap-12`,
  },
  lg: {
    0: tw`lg:gap-0`,
    1: tw`lg:gap-1`,
    2: tw`lg:gap-2`,
    3: tw`lg:gap-3`,
    4: tw`lg:gap-4`,
    5: tw`lg:gap-5`,
    6: tw`lg:gap-6`,
    7: tw`lg:gap-7`,
    8: tw`lg:gap-8`,
    9: tw`lg:gap-9`,
    10: tw`lg:gap-10`,
    11: tw`lg:gap-11`,
    12: tw`lg:gap-12`,
  },
  xl: {
    0: tw`xl:gap-0`,
    1: tw`xl:gap-1`,
    2: tw`xl:gap-2`,
    3: tw`xl:gap-3`,
    4: tw`xl:gap-4`,
    5: tw`xl:gap-5`,
    6: tw`xl:gap-6`,
    7: tw`xl:gap-7`,
    8: tw`xl:gap-8`,
    9: tw`xl:gap-9`,
    10: tw`xl:gap-10`,
    11: tw`xl:gap-11`,
    12: tw`xl:gap-12`,
  },
} as const

export const GRID_ROW_GAP: ScreenStyle<GridGapAmount> = {
  default: {
    0: tw`gap-y-0`,
    1: tw`gap-y-1`,
    2: tw`gap-y-2`,
    3: tw`gap-y-3`,
    4: tw`gap-y-4`,
    5: tw`gap-y-5`,
    6: tw`gap-y-6`,
    7: tw`gap-y-7`,
    8: tw`gap-y-8`,
    9: tw`gap-y-9`,
    10: tw`gap-y-10`,
    11: tw`gap-y-11`,
    12: tw`gap-y-12`,
  },
  xs: {
    0: tw`xs:gap-y-0`,
    1: tw`xs:gap-y-1`,
    2: tw`xs:gap-y-2`,
    3: tw`xs:gap-y-3`,
    4: tw`xs:gap-y-4`,
    5: tw`xs:gap-y-5`,
    6: tw`xs:gap-y-6`,
    7: tw`xs:gap-y-7`,
    8: tw`xs:gap-y-8`,
    9: tw`xs:gap-y-9`,
    10: tw`xs:gap-y-10`,
    11: tw`xs:gap-y-11`,
    12: tw`xs:gap-y-12`,
  },
  sm: {
    0: tw`sm:gap-y-0`,
    1: tw`sm:gap-y-1`,
    2: tw`sm:gap-y-2`,
    3: tw`sm:gap-y-3`,
    4: tw`sm:gap-y-4`,
    5: tw`sm:gap-y-5`,
    6: tw`sm:gap-y-6`,
    7: tw`sm:gap-y-7`,
    8: tw`sm:gap-y-8`,
    9: tw`sm:gap-y-9`,
    10: tw`sm:gap-y-10`,
    11: tw`sm:gap-y-11`,
    12: tw`sm:gap-y-12`,
  },
  md: {
    0: tw`md:gap-y-0`,
    1: tw`md:gap-y-1`,
    2: tw`md:gap-y-2`,
    3: tw`md:gap-y-3`,
    4: tw`md:gap-y-4`,
    5: tw`md:gap-y-5`,
    6: tw`md:gap-y-6`,
    7: tw`md:gap-y-7`,
    8: tw`md:gap-y-8`,
    9: tw`md:gap-y-9`,
    10: tw`md:gap-y-10`,
    11: tw`md:gap-y-11`,
    12: tw`md:gap-y-12`,
  },
  lg: {
    0: tw`lg:gap-y-0`,
    1: tw`lg:gap-y-1`,
    2: tw`lg:gap-y-2`,
    3: tw`lg:gap-y-3`,
    4: tw`lg:gap-y-4`,
    5: tw`lg:gap-y-5`,
    6: tw`lg:gap-y-6`,
    7: tw`lg:gap-y-7`,
    8: tw`lg:gap-y-8`,
    9: tw`lg:gap-y-9`,
    10: tw`lg:gap-y-10`,
    11: tw`lg:gap-y-11`,
    12: tw`lg:gap-y-12`,
  },
  xl: {
    0: tw`xl:gap-y-0`,
    1: tw`xl:gap-y-1`,
    2: tw`xl:gap-y-2`,
    3: tw`xl:gap-y-3`,
    4: tw`xl:gap-y-4`,
    5: tw`xl:gap-y-5`,
    6: tw`xl:gap-y-6`,
    7: tw`xl:gap-y-7`,
    8: tw`xl:gap-y-8`,
    9: tw`xl:gap-y-9`,
    10: tw`xl:gap-y-10`,
    11: tw`xl:gap-y-11`,
    12: tw`xl:gap-y-12`,
  },
} as const

export const GRID_COL_GAP: ScreenStyle<GridGapAmount> = {
  default: {
    0: tw`gap-x-0`,
    1: tw`gap-x-1`,
    2: tw`gap-x-2`,
    3: tw`gap-x-3`,
    4: tw`gap-x-4`,
    5: tw`gap-x-5`,
    6: tw`gap-x-6`,
    7: tw`gap-x-7`,
    8: tw`gap-x-8`,
    9: tw`gap-x-9`,
    10: tw`gap-x-10`,
    11: tw`gap-x-11`,
    12: tw`gap-x-12`,
  },
  xs: {
    0: tw`xs:gap-x-0`,
    1: tw`xs:gap-x-1`,
    2: tw`xs:gap-x-2`,
    3: tw`xs:gap-x-3`,
    4: tw`xs:gap-x-4`,
    5: tw`xs:gap-x-5`,
    6: tw`xs:gap-x-6`,
    7: tw`xs:gap-x-7`,
    8: tw`xs:gap-x-8`,
    9: tw`xs:gap-x-9`,
    10: tw`xs:gap-x-10`,
    11: tw`xs:gap-x-11`,
    12: tw`xs:gap-x-12`,
  },
  sm: {
    0: tw`sm:gap-x-0`,
    1: tw`sm:gap-x-1`,
    2: tw`sm:gap-x-2`,
    3: tw`sm:gap-x-3`,
    4: tw`sm:gap-x-4`,
    5: tw`sm:gap-x-5`,
    6: tw`sm:gap-x-6`,
    7: tw`sm:gap-x-7`,
    8: tw`sm:gap-x-8`,
    9: tw`sm:gap-x-9`,
    10: tw`sm:gap-x-10`,
    11: tw`sm:gap-x-11`,
    12: tw`sm:gap-x-12`,
  },
  md: {
    0: tw`md:gap-x-0`,
    1: tw`md:gap-x-1`,
    2: tw`md:gap-x-2`,
    3: tw`md:gap-x-3`,
    4: tw`md:gap-x-4`,
    5: tw`md:gap-x-5`,
    6: tw`md:gap-x-6`,
    7: tw`md:gap-x-7`,
    8: tw`md:gap-x-8`,
    9: tw`md:gap-x-9`,
    10: tw`md:gap-x-10`,
    11: tw`md:gap-x-11`,
    12: tw`md:gap-x-12`,
  },
  lg: {
    0: tw`lg:gap-x-0`,
    1: tw`lg:gap-x-1`,
    2: tw`lg:gap-x-2`,
    3: tw`lg:gap-x-3`,
    4: tw`lg:gap-x-4`,
    5: tw`lg:gap-x-5`,
    6: tw`lg:gap-x-6`,
    7: tw`lg:gap-x-7`,
    8: tw`lg:gap-x-8`,
    9: tw`lg:gap-x-9`,
    10: tw`lg:gap-x-10`,
    11: tw`lg:gap-x-11`,
    12: tw`lg:gap-x-12`,
  },
  xl: {
    0: tw`xl:gap-x-0`,
    1: tw`xl:gap-x-1`,
    2: tw`xl:gap-x-2`,
    3: tw`xl:gap-x-3`,
    4: tw`xl:gap-x-4`,
    5: tw`xl:gap-x-5`,
    6: tw`xl:gap-x-6`,
    7: tw`xl:gap-x-7`,
    8: tw`xl:gap-x-8`,
    9: tw`xl:gap-x-9`,
    10: tw`xl:gap-x-10`,
    11: tw`xl:gap-x-11`,
    12: tw`xl:gap-x-12`,
  },
} as const

export const GRID_COL_SPAN: ScreenStyle<GridColSpanAmount> = {
  default: {
    auto: tw`col-auto`,
    1: tw`col-span-1`,
    2: tw`col-span-2`,
    3: tw`col-span-3`,
    4: tw`col-span-4`,
    5: tw`col-span-5`,
    6: tw`col-span-6`,
    7: tw`col-span-7`,
    8: tw`col-span-8`,
    9: tw`col-span-9`,
    10: tw`col-span-10`,
    11: tw`col-span-11`,
    12: tw`col-span-12`,
  },
  xs: {
    auto: tw`col-auto`,
    1: tw`xs:col-span-1`,
    2: tw`xs:col-span-2`,
    3: tw`xs:col-span-3`,
    4: tw`xs:col-span-4`,
    5: tw`xs:col-span-5`,
    6: tw`xs:col-span-6`,
    7: tw`xs:col-span-7`,
    8: tw`xs:col-span-8`,
    9: tw`xs:col-span-9`,
    10: tw`xs:col-span-10`,
    11: tw`xs:col-span-11`,
    12: tw`xs:col-span-12`,
  },
  sm: {
    auto: tw`col-auto`,
    1: tw`sm:col-span-1`,
    2: tw`sm:col-span-2`,
    3: tw`sm:col-span-3`,
    4: tw`sm:col-span-4`,
    5: tw`sm:col-span-5`,
    6: tw`sm:col-span-6`,
    7: tw`sm:col-span-7`,
    8: tw`sm:col-span-8`,
    9: tw`sm:col-span-9`,
    10: tw`sm:col-span-10`,
    11: tw`sm:col-span-11`,
    12: tw`sm:col-span-12`,
  },
  md: {
    auto: tw`col-auto`,
    1: tw`md:col-span-1`,
    2: tw`md:col-span-2`,
    3: tw`md:col-span-3`,
    4: tw`md:col-span-4`,
    5: tw`md:col-span-5`,
    6: tw`md:col-span-6`,
    7: tw`md:col-span-7`,
    8: tw`md:col-span-8`,
    9: tw`md:col-span-9`,
    10: tw`md:col-span-10`,
    11: tw`md:col-span-11`,
    12: tw`md:col-span-12`,
  },
  lg: {
    auto: tw`col-auto`,
    1: tw`lg:col-span-1`,
    2: tw`lg:col-span-2`,
    3: tw`lg:col-span-3`,
    4: tw`lg:col-span-4`,
    5: tw`lg:col-span-5`,
    6: tw`lg:col-span-6`,
    7: tw`lg:col-span-7`,
    8: tw`lg:col-span-8`,
    9: tw`lg:col-span-9`,
    10: tw`lg:col-span-10`,
    11: tw`lg:col-span-11`,
    12: tw`lg:col-span-12`,
  },
  xl: {
    auto: tw`col-auto`,
    1: tw`xl:col-span-1`,
    2: tw`xl:col-span-2`,
    3: tw`xl:col-span-3`,
    4: tw`xl:col-span-4`,
    5: tw`xl:col-span-5`,
    6: tw`xl:col-span-6`,
    7: tw`xl:col-span-7`,
    8: tw`xl:col-span-8`,
    9: tw`xl:col-span-9`,
    10: tw`xl:col-span-10`,
    11: tw`xl:col-span-11`,
    12: tw`xl:col-span-12`,
  },
} as const

export const GRID_COL_START: ScreenStyle<GridColStartAmount> = {
  default: {
    1: tw`col-start-1`,
    2: tw`col-start-2`,
    3: tw`col-start-3`,
    4: tw`col-start-4`,
    5: tw`col-start-5`,
    6: tw`col-start-6`,
    7: tw`col-start-7`,
    8: tw`col-start-8`,
    9: tw`col-start-9`,
    10: tw`col-start-10`,
    11: tw`col-start-11`,
    12: tw`col-start-12`,
    13: tw`col-start-13`,
  },
  xs: {
    1: tw`xs:col-start-1`,
    2: tw`xs:col-start-2`,
    3: tw`xs:col-start-3`,
    4: tw`xs:col-start-4`,
    5: tw`xs:col-start-5`,
    6: tw`xs:col-start-6`,
    7: tw`xs:col-start-7`,
    8: tw`xs:col-start-8`,
    9: tw`xs:col-start-9`,
    10: tw`xs:col-start-10`,
    11: tw`xs:col-start-11`,
    12: tw`xs:col-start-12`,
    13: tw`xs:col-start-13`,
  },
  sm: {
    1: tw`sm:col-start-1`,
    2: tw`sm:col-start-2`,
    3: tw`sm:col-start-3`,
    4: tw`sm:col-start-4`,
    5: tw`sm:col-start-5`,
    6: tw`sm:col-start-6`,
    7: tw`sm:col-start-7`,
    8: tw`sm:col-start-8`,
    9: tw`sm:col-start-9`,
    10: tw`sm:col-start-10`,
    11: tw`sm:col-start-11`,
    12: tw`sm:col-start-12`,
    13: tw`sm:col-start-13`,
  },
  md: {
    1: tw`md:col-start-1`,
    2: tw`md:col-start-2`,
    3: tw`md:col-start-3`,
    4: tw`md:col-start-4`,
    5: tw`md:col-start-5`,
    6: tw`md:col-start-6`,
    7: tw`md:col-start-7`,
    8: tw`md:col-start-8`,
    9: tw`md:col-start-9`,
    10: tw`md:col-start-10`,
    11: tw`md:col-start-11`,
    12: tw`md:col-start-12`,
    13: tw`md:col-start-13`,
  },
  lg: {
    1: tw`lg:col-start-1`,
    2: tw`lg:col-start-2`,
    3: tw`lg:col-start-3`,
    4: tw`lg:col-start-4`,
    5: tw`lg:col-start-5`,
    6: tw`lg:col-start-6`,
    7: tw`lg:col-start-7`,
    8: tw`lg:col-start-8`,
    9: tw`lg:col-start-9`,
    10: tw`lg:col-start-10`,
    11: tw`lg:col-start-11`,
    12: tw`lg:col-start-12`,
    13: tw`lg:col-start-13`,
  },
  xl: {
    1: tw`xl:col-start-1`,
    2: tw`xl:col-start-2`,
    3: tw`xl:col-start-3`,
    4: tw`xl:col-start-4`,
    5: tw`xl:col-start-5`,
    6: tw`xl:col-start-6`,
    7: tw`xl:col-start-7`,
    8: tw`xl:col-start-8`,
    9: tw`xl:col-start-9`,
    10: tw`xl:col-start-10`,
    11: tw`xl:col-start-11`,
    12: tw`xl:col-start-12`,
    13: tw`xl:col-start-13`,
  },
} as const

export const GRID_COL_END: ScreenStyle<GridColStartAmount> = {
  default: {
    1: tw`col-end-1`,
    2: tw`col-end-2`,
    3: tw`col-end-3`,
    4: tw`col-end-4`,
    5: tw`col-end-5`,
    6: tw`col-end-6`,
    7: tw`col-end-7`,
    8: tw`col-end-8`,
    9: tw`col-end-9`,
    10: tw`col-end-10`,
    11: tw`col-end-11`,
    12: tw`col-end-12`,
    13: tw`col-end-13`,
  },
  xs: {
    1: tw`xs:col-end-1`,
    2: tw`xs:col-end-2`,
    3: tw`xs:col-end-3`,
    4: tw`xs:col-end-4`,
    5: tw`xs:col-end-5`,
    6: tw`xs:col-end-6`,
    7: tw`xs:col-end-7`,
    8: tw`xs:col-end-8`,
    9: tw`xs:col-end-9`,
    10: tw`xs:col-end-10`,
    11: tw`xs:col-end-11`,
    12: tw`xs:col-end-12`,
    13: tw`xs:col-end-13`,
  },
  sm: {
    1: tw`sm:col-end-1`,
    2: tw`sm:col-end-2`,
    3: tw`sm:col-end-3`,
    4: tw`sm:col-end-4`,
    5: tw`sm:col-end-5`,
    6: tw`sm:col-end-6`,
    7: tw`sm:col-end-7`,
    8: tw`sm:col-end-8`,
    9: tw`sm:col-end-9`,
    10: tw`sm:col-end-10`,
    11: tw`sm:col-end-11`,
    12: tw`sm:col-end-12`,
    13: tw`sm:col-end-13`,
  },
  md: {
    1: tw`md:col-end-1`,
    2: tw`md:col-end-2`,
    3: tw`md:col-end-3`,
    4: tw`md:col-end-4`,
    5: tw`md:col-end-5`,
    6: tw`md:col-end-6`,
    7: tw`md:col-end-7`,
    8: tw`md:col-end-8`,
    9: tw`md:col-end-9`,
    10: tw`md:col-end-10`,
    11: tw`md:col-end-11`,
    12: tw`md:col-end-12`,
    13: tw`md:col-end-13`,
  },
  lg: {
    1: tw`lg:col-end-1`,
    2: tw`lg:col-end-2`,
    3: tw`lg:col-end-3`,
    4: tw`lg:col-end-4`,
    5: tw`lg:col-end-5`,
    6: tw`lg:col-end-6`,
    7: tw`lg:col-end-7`,
    8: tw`lg:col-end-8`,
    9: tw`lg:col-end-9`,
    10: tw`lg:col-end-10`,
    11: tw`lg:col-end-11`,
    12: tw`lg:col-end-12`,
    13: tw`lg:col-end-13`,
  },
  xl: {
    1: tw`xl:col-end-1`,
    2: tw`xl:col-end-2`,
    3: tw`xl:col-end-3`,
    4: tw`xl:col-end-4`,
    5: tw`xl:col-end-5`,
    6: tw`xl:col-end-6`,
    7: tw`xl:col-end-7`,
    8: tw`xl:col-end-8`,
    9: tw`xl:col-end-9`,
    10: tw`xl:col-end-10`,
    11: tw`xl:col-end-11`,
    12: tw`xl:col-end-12`,
    13: tw`xl:col-end-13`,
  },
} as const

export const GRID_ROW_SPAN: ScreenStyle<GridRowSpanAmount> = {
  default: {
    1: tw`row-span-1`,
    2: tw`row-span-2`,
    3: tw`row-span-3`,
    4: tw`row-span-4`,
    5: tw`row-span-5`,
    6: tw`row-span-6`,
  },
  xs: {
    1: tw`xs:row-span-1`,
    2: tw`xs:row-span-2`,
    3: tw`xs:row-span-3`,
    4: tw`xs:row-span-4`,
    5: tw`xs:row-span-5`,
    6: tw`xs:row-span-6`,
  },
  sm: {
    1: tw`sm:row-span-1`,
    2: tw`sm:row-span-2`,
    3: tw`sm:row-span-3`,
    4: tw`sm:row-span-4`,
    5: tw`sm:row-span-5`,
    6: tw`sm:row-span-6`,
  },
  md: {
    1: tw`md:row-span-1`,
    2: tw`md:row-span-2`,
    3: tw`md:row-span-3`,
    4: tw`md:row-span-4`,
    5: tw`md:row-span-5`,
    6: tw`md:row-span-6`,
  },
  lg: {
    1: tw`lg:row-span-1`,
    2: tw`lg:row-span-2`,
    3: tw`lg:row-span-3`,
    4: tw`lg:row-span-4`,
    5: tw`lg:row-span-5`,
    6: tw`lg:row-span-6`,
  },
  xl: {
    1: tw`xl:row-span-1`,
    2: tw`xl:row-span-2`,
    3: tw`xl:row-span-3`,
    4: tw`xl:row-span-4`,
    5: tw`xl:row-span-5`,
    6: tw`xl:row-span-6`,
  },
} as const

export const GRID_ROW_START: ScreenStyle<GridRowStartAmount> = {
  default: {
    1: tw`row-start-1`,
    2: tw`row-start-2`,
    3: tw`row-start-3`,
    4: tw`row-start-4`,
    5: tw`row-start-5`,
    6: tw`row-start-6`,
    7: tw`row-start-7`,
  },
  xs: {
    1: tw`xs:row-start-1`,
    2: tw`xs:row-start-2`,
    3: tw`xs:row-start-3`,
    4: tw`xs:row-start-4`,
    5: tw`xs:row-start-5`,
    6: tw`xs:row-start-6`,
    7: tw`xs:row-start-7`,
  },
  sm: {
    1: tw`sm:row-start-1`,
    2: tw`sm:row-start-2`,
    3: tw`sm:row-start-3`,
    4: tw`sm:row-start-4`,
    5: tw`sm:row-start-5`,
    6: tw`sm:row-start-6`,
    7: tw`sm:row-start-7`,
  },
  md: {
    1: tw`md:row-start-1`,
    2: tw`md:row-start-2`,
    3: tw`md:row-start-3`,
    4: tw`md:row-start-4`,
    5: tw`md:row-start-5`,
    6: tw`md:row-start-6`,
    7: tw`md:row-start-7`,
  },
  lg: {
    1: tw`lg:row-start-1`,
    2: tw`lg:row-start-2`,
    3: tw`lg:row-start-3`,
    4: tw`lg:row-start-4`,
    5: tw`lg:row-start-5`,
    6: tw`lg:row-start-6`,
    7: tw`lg:row-start-7`,
  },
  xl: {
    1: tw`xl:row-start-1`,
    2: tw`xl:row-start-2`,
    3: tw`xl:row-start-3`,
    4: tw`xl:row-start-4`,
    5: tw`xl:row-start-5`,
    6: tw`xl:row-start-6`,
    7: tw`xl:row-start-7`,
  },
} as const

export const GRID_ROW_END: ScreenStyle<GridRowStartAmount> = {
  default: {
    1: tw`row-end-1`,
    2: tw`row-end-2`,
    3: tw`row-end-3`,
    4: tw`row-end-4`,
    5: tw`row-end-5`,
    6: tw`row-end-6`,
    7: tw`row-end-7`,
  },
  xs: {
    1: tw`xs:row-end-1`,
    2: tw`xs:row-end-2`,
    3: tw`xs:row-end-3`,
    4: tw`xs:row-end-4`,
    5: tw`xs:row-end-5`,
    6: tw`xs:row-end-6`,
    7: tw`xs:row-end-7`,
  },
  sm: {
    1: tw`sm:row-end-1`,
    2: tw`sm:row-end-2`,
    3: tw`sm:row-end-3`,
    4: tw`sm:row-end-4`,
    5: tw`sm:row-end-5`,
    6: tw`sm:row-end-6`,
    7: tw`sm:row-end-7`,
  },
  md: {
    1: tw`md:row-end-1`,
    2: tw`md:row-end-2`,
    3: tw`md:row-end-3`,
    4: tw`md:row-end-4`,
    5: tw`md:row-end-5`,
    6: tw`md:row-end-6`,
    7: tw`md:row-end-7`,
  },
  lg: {
    1: tw`lg:row-end-1`,
    2: tw`lg:row-end-2`,
    3: tw`lg:row-end-3`,
    4: tw`lg:row-end-4`,
    5: tw`lg:row-end-5`,
    6: tw`lg:row-end-6`,
    7: tw`lg:row-end-7`,
  },
  xl: {
    1: tw`xl:row-end-1`,
    2: tw`xl:row-end-2`,
    3: tw`xl:row-end-3`,
    4: tw`xl:row-end-4`,
    5: tw`xl:row-end-5`,
    6: tw`xl:row-end-6`,
    7: tw`xl:row-end-7`,
  },
} as const

export type GridWidth = Exclude<Width, 'wide'>

export const GRID_WIDTH: ScreenStyle<GridWidth> = {
  default: {
    auto: tw`w-auto`,
    full: tw`w-full`,
    fit: tw`w-fit`,
  },
  xs: {
    auto: tw`xs:w-auto`,
    full: tw`xs:w-full`,
    fit: tw`xs:w-fit`,
  },
  sm: {
    auto: tw`sm:w-auto`,
    full: tw`sm:w-full`,
    fit: tw`sm:w-fit`,
  },
  md: {
    auto: tw`md:w-auto`,
    full: tw`md:w-full`,
    fit: tw`md:w-fit`,
  },
  lg: {
    auto: tw`lg:w-auto`,
    full: tw`lg:w-full`,
    fit: tw`lg:w-fit`,
  },
  xl: {
    auto: tw`xl:w-auto`,
    full: tw`xl:w-full`,
    fit: tw`xl:w-fit`,
  },
}
