export const METADATA_BASE = {
  title: 'GAR NST2023',
  description: 'Generated by tDev',
}

export const METADATA_NOT_FOUND = {
  title: 'Not Found',
}

export const METADATA_ERROR = {
  title: 'Error',
}
