import type { Metadata } from 'next'

import clsx from 'clsx'
import { Inter } from 'next/font/google'
import 'tw-elements/dist/css/tw-elements.min.css'

import './css/global.css'
import './css/reset.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className='dark'>
      <body className={clsx(inter.className, 'dark:bg-zinc-800')}>
        {children}
      </body>
    </html>
  )
}
