import type { Metadata } from 'next'

import { Inter } from 'next/font/google'

import './globals.css'
import { AllProvider } from './provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html suppressHydrationWarning>
      <body className={inter.className}>
        <time dateTime={new Date().toISOString()} suppressHydrationWarning />

        <AllProvider>{children}</AllProvider>
      </body>
    </html>
  )
}
