import type { Metadata } from 'next'

import dynamic from 'next/dynamic'

import { AppContainer } from '@/components/AppContainer'

const DynamicComponent = dynamic(() => import('@/components/BaseLayout'), {
  ssr: false,
})

type AppProps = {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: 'GAR NST2023',
  description: 'Generated by tDev',
}

export default function RootLayout({ children }: AppProps) {
  return (
    <AppContainer>
      <DynamicComponent>{children}</DynamicComponent>
    </AppContainer>
  )
}
