export enum ELEMENT_ID {
  BASIC_GRID = 'basic-grid',
  GAP = 'gap',
  ROW_GAP = 'row-gap',
  COL_GAP = 'col-gap',
  RESPONSIVE = 'responsive',
  SPAN = 'span',
  ROW_SPAN = 'row-span',
  COL_SPAN = 'col-span',
  RESPONSIVE_SPAN = 'responsive-span',
  PLACEMENT = 'placement',
  ALIGN_ITEMS = 'align-items',
  ALIGN_SELF = 'align-self',
  JUSTIFY_ITEMS = 'justify-items',
}
