name: Generate Changelog
on:
  release:
    types:
      - created
  pull_request:
    branches:
      - main
      - dev
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: "✏️ Generate release changelog"
        uses: ardalanamini/auto-changelog@v4
        id  : changelog
        with:
          github-token            : ${{ github.token }}
          commit-types            : |
            feat: New Features
            fix: Bug Fixes
            build: Build System & Dependencies
            perf: Performance Improvements
            docs: Documentation
            test: Tests
            refactor: Refactors
            chore: Chores
            ci: CI
            style: Code Style
            revert: Reverts
          default-commit-type     : Other Changes
          release-name            : v1.0.0
          release-name-prefix     : ""
          mention-authors         : true
          mention-new-contributors: true
          include-compare-link    : true
          include-pr-links        : true
          include-commit-links    : true
          semver                  : true
          use-github-autolink     : true